[package]
name = "quasim"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
array-init = "2.1.0"
divan = "0.1.21"
nalgebra.workspace = true
rand = "0.9.2"
thiserror = "2.0.18"
oq3_syntax = "0.7.0"
log.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
rayon = "1.11.0"

[dev-dependencies]
tracking-allocator = "0.4.0"

[[bench]]
name = "debug-simulator"
harness = false

[[bench]]
name = "simulator-comparison"
harness = false
