[package]
name = "deutsch-jozsa"
version = "0.1.0"
edition = "2024"

[features]
default = []
gpu = ["quasim/gpu"]
wgpu = ["gpu", "quasim/wgpu"]
cuda = ["gpu", "quasim/cuda"]
cpu = ["gpu", "quasim/cpu"]
hip = ["gpu", "quasim/hip"]

[dependencies]
quasim = { path = "../../quasim" }

[dev-dependencies]
divan = "0.1.21"

[[bench]]
name = "deutsch-jozsa-benchmark"
harness = false
