name: pull.yml
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  RUSTFLAGS: "-D warnings"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: swatinem/rust-cache@v2
      - run: ./.github/check.sh
